[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" }, cargo = { allFeatures = true }}


[[language]]
name = "python"

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python"
args = ["-m",  "debugpy.adapter"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }



#TODO: LATEX
#[[language]]
#name = "latex"
#
#[language.config.texlab.build]
#onSave = true
#forwardSearchAfter = true
#
#[language.config.texlab.forwardSearch]
#executable = "zathura"
#args = [ "--synctex-forward", "%l:1:%f", "%p" ]
#
#[language.config.texlab.chktex]
#onEdit = true

# DOC: CHECK: `hx --health xxx`
# TODO: Install LSP
#   - awk-language-server (https://github.com/Beaglefoot/awk-language-server)
#   - ruff (https://github.com/astral-sh/ruff-lsp)
